/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Fixture } from "./Fixture";
import { FixtureCountArgs } from "./FixtureCountArgs";
import { FixtureFindManyArgs } from "./FixtureFindManyArgs";
import { FixtureFindUniqueArgs } from "./FixtureFindUniqueArgs";
import { DeleteFixtureArgs } from "./DeleteFixtureArgs";
import { FixtureService } from "../fixture.service";
@graphql.Resolver(() => Fixture)
export class FixtureResolverBase {
  constructor(protected readonly service: FixtureService) {}

  async _fixturesMeta(
    @graphql.Args() args: FixtureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Fixture])
  async fixtures(
    @graphql.Args() args: FixtureFindManyArgs
  ): Promise<Fixture[]> {
    return this.service.fixtures(args);
  }

  @graphql.Query(() => Fixture, { nullable: true })
  async fixture(
    @graphql.Args() args: FixtureFindUniqueArgs
  ): Promise<Fixture | null> {
    const result = await this.service.fixture(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fixture)
  async deleteFixture(
    @graphql.Args() args: DeleteFixtureArgs
  ): Promise<Fixture | null> {
    try {
      return await this.service.deleteFixture(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
